[package]
name = "wasp"
version = "0.1.0"
authors = ["Ishimoto Shinobu <nagakamira@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.2"
